--2022/11/08
--1번 문제 : EMPLOYEES 테이블에서 SALARY가 8000 이상인 직원의 수를 조회
SELECT COUNT(*) FROM EMPLOYEES
WHERE SALARY>=8000;

--2번 문제 : EMPLOYEES 테이블에서 HIRE_DATE가 2007년 1월 1일 이후인
--직원의 수를 조회
SELECT COUNT(*) FROM EMPLOYEES
WHERE HIRE_DATE>TO_DATE('07/01/01');

--3번 문제 : JOBS 테이블에서 MAX_SALARY 값의 합계와 평균을 조회
SELECT SUM(MAX_SALARY), AVG(MAX_SALARY) FROM JOBS;

--4번 문제 : EMPLOYEES 테이블에서 JOB_ID가 'IT_PROG'인 직원의
--SALARY 합계와 평균을 조회
SELECT SUM(SALARY), AVG(SALARY) FROM EMPLOYEES
WHERE JOB_ID='IT_PROG';

--5번 문제 : EMPLOYEES 테이블에서 DEPARTMENT_ID가 50과 80사이인 직원의
--FIRST_NAME,SALARY,COMMISSION_PCT의 평균값을 FIRST_NAME정렬 기준으로 조회
--(NULL 값은 0으로 출력)
SELECT FIRST_NAME, SALARY, ROUND(AVG(NVL(COMMISSION_PCT,0)),2)
FROM EMPLOYEES
WHERE DEPARTMENT_ID BETWEEN 50 AND 80
GROUP BY FIRST_NAME, SALARY
ORDER BY FIRST_NAME;