--2022/11/10 Chap 09, Chap 10
--서브쿼리
SELECT SAL
    FROM EMP
    WHERE ENAME = 'JONES';

SELECT *
    FROM EMP
    WHERE SAL > 2975;

SELECT *
    FROM EMP
    WHERE SAL > (
        SELECT SAL
            FROM EMP
            WHERE ENAME = 'JONES'
        );

--Chap 10
--테이블에 데이터 추가하기
CREATE TABLE DEPT_TEMP
AS SELECT * FROM DEPT;
 
SELECT * FROM DEPT_TMP;
 
--P.267 복습문제
CREATE TABLE EMP_TEMP
AS SELECT * FROM EMP;
 
SELECT * FROM EMP_TEMP;
 
--테이블 삭제하기
DROP TABLE DEPT_TEMP;
DROP TABLE EMP_TEMP;
 
--INSERT문
SELECT * FROM DEPT_TEMP;

INSERT INTO DEPT_TEMP(DEPTNO, DNAME, LOC)
VALUES(50, '지원', '안양');

INSERT INTO DEPT_TEMP(DEPTNO, DNAME, LOC)
VALUES(60, 'NETWORK', '수원');

COMMIT;

INSERT INTO DEPT_TEMP
VALUES(70, '경영', '부산');

INSERT INTO DEPT_TEMP(DEPTNO, DNAME, LOC)
VALUES(90, '경영2', NULL);

SELECT * FROM DEPT_TEMP;

DROP TABLE EMP_TEMP;

CREATE TABLE EMP_TEMP
    AS SELECT * FROM EMP
    WHERE 1<>1;
    
SELECT * FROM EMP_TEMP;
SELECT * FROM EMP;

DESC EMP_TEMP;

INSERT INTO EMP_TEMP(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES(9999,'김대철','강사',0000,'2022-11-10',2500,50,40);

INSERT INTO EMP_TEMP(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES(1111,'홍길동','강사',0000,SYSDATE,3500,40,50);

--서브쿼리를 사용하여 한 번에 여러 데이터 추가하기
INSERT INTO EMP_TEMP(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
SELECT EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO
FROM EMP;

COMMIT;
ROLLBACK;

SELECT * FROM EMP_TEMP;

--테이블에 있는 데이터 수정하기
--UPDATE문
--데이터 전체수정하기
UPDATE EMP_TEMP
SET SAL = SAL+10000;

SELECT * FROM EMP_TEMP;

--데이터 일부 수정하기
UPDATE EMP_TEMP
SET SAL = 10
WHERE ENAME = '김대철';

SELECT * FROM EMP_TEMP;

--데이터 삭제하기
DELETE FROM EMP_TEMP
WHERE SAL >= 2000;

SELECT * FROM EMP_TEMP;
ROLLBACK;