--2022/11/11 Chap 12 데이터 정의어
--테이블을 생성하는 CREATE
--P.313 실습 12-1
CREATE TABLE EMP_DDL(
    EMPNO       NUMBER(4),
    ENAME       VARCHAR2(10),
    JOB         VARCHAR2(9),
    MGR         NUMBER(4),
    HIREDATE    DATE,
    SAL         NUMBER(7,2),
    COMM        NUMBER(7,2),
    DEPTNO      NUMBER(2)
);

SELECT * FROM EMP_DDL;

--테이블을 변경하는 ALTER
--P.317 실습 12-6
CREATE TABLE EMP_ALTER
AS SELECT*FROM EMP;

SELECT * FROM EMP_ALTER;

--테이블에 열  추가하는 ADD
--P.318 실습 12-7
ALTER TABLE EMP_ALTER
ADD HP VARCHAR2(20);

SELECT * FROM EMP_ALTER;

--열 이름을 변경하는 RNAME
--P.318 실습 12-8
ALTER TABLE EMP_ALTER
RENAME COLUMN HP TO TEL;

ALTER TABLE EMP_ALTER
RENAME COLUMN COMM TO 보너스;

SELECT * FROM EMP_ALTER;

--열의 자료형을 변경하는 MODIFY
--P.319 실습 12-9
DESC EMP_ALTER;

ALTER TABLE EMP_ALTER
MODIFY EMPNO NUMBER(5);

DESC EMP_ALTER;

--특정 열을 삭제할 때 사용하는 DROP
--P.319 실습 12-10
SELECT * FROM EMP_ALTER;

ALTER TABLE EMP_ALTER
DROP COLUMN TEL;

SELECT * FROM EMP_ALTER;

--테이블 이름을 변경하는 RNAME
--P.321 실습 12-11
RENAME EMP_ALTER TO EMP_RENAME;

--테이블의 데이터를 삭제하는 TRUNCATE
--P.322 실습 12-14 
TRUNCATE TABLE EMP_RENAME;

SELECT * FROM EMP_RENAME;

--테이블을 삭제하는 DROP
--P.323 실습 12-15
DROP TABLE EMP_RENAME;

--Chap 13 객체 종류
--P.341 실습 13-15
CREATE VIEW VW_EMP20
    AS(SELECT EMPNO,ENAME,JOB,DEPTNO
        FROM EMP
        WHERE DEPTNO=20);

--P.341 실습 13-16
SELECT * FROM USER_VIEWS;

--시퀸스
--P.349 실습 13-26
CREATE TABLE DEPT_SQL
        AS SELECT *
        FROM DEPT
        WHERE 1<>1;

SELECT*FROM DEPT_SQL;

--P.350 실습 13-27
CREATE SEQUENCE SEQ_DEPT_SEQUENCE
    INCREMENT BY 10
    START WITH 10
    MAXVALUE 90
    MINVALUE 0
    NOCYCLE
    CACHE 2;

--P.350 실습 13-28
SELECT * FROM USER_SEQUENCES;

--P.350 실습 13-29
INSERT INTO DEPT_SQL(DEPTNO,DNAME,LOC)
VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL,'JAVA','SUWON');

INSERT INTO DEPT_SQL(DEPTNO,DNAME,LOC)
VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL,'SQL','BUSAN');

INSERT INTO DEPT_SQL(DEPTNO,DNAME,LOC)
VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL,'DATABASE','SEOUL');

SELECT * FROM DEPT_SQL;