--2022/11/04 Chap 06
--문자 데이터를 가공하는 문자 함수
SELECT ENAME AS 이름, UPPER(ename) as 대문자, lower(ename) as 소문자, INITCAP(ename) as 첫글자만대문자 from emp;

SELECT ENAME, LENGTH(ENAME) FROM EMP;

SELECT ENAME, LENGTH(ENAME) FROM EMP
WHERE LENGTH(ENAME)>=5;

SELECT JOB, SUBSTR(JOB,1,2), SUBSTR(JOB,3,2), SUBSTR(JOB,5) FROM EMP;

SELECT INSTR('HELLP, ORACLE!','L',2,4) FROM DUAL;

SELECT SYSDATE FROM DUAL;

SELECT * FROM EMP WHERE INSTR(ENAME,'S')>0;

--수치를 조정하는 숫자함수
SELECT ROUND(1234.5645,2) AS ROUND FROM DUAL;
SELECT ROUND(1234.5645,-3) AS ROUND FROM DUAL;

--형 변환 함수
SELECT SYSDATE FROM DUAL;
SELECT SYSDATE-1 FROM DUAL;

SELECT EMPNO, ENAME, HIREDATE, ADD_MONTHS(HIREDATE,120) AS WORK10YEAR FROM EMP;

SELECT EMPNO, ENAME, EMPNO + '500' FROM EMP;
SELECT EMPNO, ENAME, TO_CHAR(EMPNO) + '500' FROM EMP;

SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD HH24:MI:SS') AS 시간 FROM DUAL;

--NULL 처리 함수
SELECT EMPNO, ENAME, SAL, COMM, SAL+COMM, NVL(COMM,0), SAL+NVL(COMM,0)
FROM EMP;
SELECT EMPNO, ENAME, COMM, NVL2(COMM,'0','X'),
NVL2(COMM, SAL*12+COMM,SAL*12) AS 연봉 FROM EMP;

SELECT EMPNO, ENAME, COMM, NVL2(COMM,'0','X'),
TO_CHAR(NVL2(COMM, SAL*12+COMM,SAL*12), '999,999,999') AS 연봉 FROM EMP;

--DECODE 함수
SELECT EMPNO, ENAME, JOB, SAL,
DECODE(JOB, 'MANAGER', SAL*1.1, 'SALESMAN', SAL*1.05, 'ANALYST',SAL,SAL*1.03)
AS UPSAL FROM EMP;