--2022/11/08 Chap07
--다중행 함수
--SUM 함수
SELECT SUM(DISTINCT SAL), SUM(ALL SAL), SUM(SAL) FROM EMP;

--COUNT 함수
SELECT COUNT(SAL) FROM EMP;
SELECT COUNT(*) FROM EMP WHERE DEPTNO=30;
SELECT COUNT(COMM) FROM EMP WHERE COMM IS NULL; --NULL값은 카운팅 되지 않음.
SELECT COUNT(COMM) FROM EMP WHERE COMM IS NOT NULL;

--MAX, MIN 함수
SELECT MAX(SAL) FROM EMP WHERE DEPTNO=30;
SELECT MAX(HIREDATE) FROM EMP WHERE DEPTNO=20;

--AVG 함수
SELECT TRUNC(AVG(SAL),2) FROM EMP WHERE DEPTNO=30;
SELECT AVG(COMM) FROM EMP WHERE DEPTNO=30;

--GROUP BY절
SELECT DEPTNO, ROUND(AVG(SAL),2) FROM EMP GROUP BY DEPTNO;
SELECT DEPTNO, AVG(COMM) FROM EMP WHERE DEPTNO=30
GROUP BY DEPTNO;

SELECT DEPTNO, AVG(COMM) FROM EMP GROUP BY DEPTNO;

--GROUP BY절에 조건을 줄 때 사용하는 HAVING절
SELECT JOB, AVG(SAL) FROM EMP
GROUP BY JOB HAVING AVG(SAL)>2500; --WHERE, HAVING(GROUP BY 같이간다.)

--WHERE절과 HAVING절의 차이
SELECT DEPTNO, JOB, AVG(SAL) FROM EMP
GROUP BY DEPTNO, JOB
HAVING AVG(SAL)>=2000
ORDER BY DEPTNO, JOB;

SELECT DEPTNO, JOB, AVG(SAL) FROM EMP
WHERE SAL<=3000
GROUP BY DEPTNO, JOB
HAVING AVG(SAL)>=2000
ORDER BY DEPTNO, JOB;

--P.194 복습문제
SELECT DEPTNO, JOB, AVG(SAL) FROM EMP
GROUP BY DEPTNO, JOB
HAVING AVG(SAL)>=500
ORDER BY DEPTNO, JOB;
