--2022/11/08
--P.212~213 연습문제
--1번 문제
SELECT DEPTNO, ENAME FROM EMP ORDER BY DEPTNO;

SELECT DEPTNO, TRUNC(AVG(SAL),0) AS AVG_SAL,
MAX(SAL), MIN(SAL), COUNT(EMPNO) AS CNT
FROM EMP GROUP BY DEPTNO;

--2번 문제
SELECT JOB, COUNT(*) FROM EMP
GROUP BY JOB HAVING COUNT(*)>=3;

--3번 문제
SELECT TO_CHAR(HIREDATE, 'YYYY') AS HIER_YEAR, DEPTNO, COUNT(*) AS CNT
FROM EMP GROUP BY TO_CHAR(HIREDATE, 'YYYY'), DEPTNO
ORDER BY TO_CHAR(HIREDATE, 'YYYY'), DEPTNO DESC;

--4번 문제
SELECT NVL2(COMM,'O','X') AS EXIST_COMM, COUNT(*) FROM EMP
GROUP BY NVL2(COMM,'O','X');

--5번 문제
SELECT DEPTNO, TO_CHAR(HIREDATE, 'YYYY') AS HIER_YEAR,
COUNT(*) AS CNT, MAX(SAL) AS MAX_SAL, MIN(SAL) AS MIN_SAL,
SUM(SAL) AS SUM_SAL, AVG(SAL) AS AVG_SAL FROM EMP
GROUP BY ROLLUP(DEPTNO, TO_CHAR(HIREDATE, 'YYYY'));

SELECT DEPTNO, TO_CHAR(HIREDATE, 'YYYY') AS HIER_YEAR,
COUNT(*) AS CNT, MAX(SAL) AS MAX_SAL, MIN(SAL) AS MIN_SAL,
SUM(SAL) AS SUM_SAL, TRUNC(AVG(SAL)) AS AVG_SAL FROM EMP
GROUP BY ROLLUP(DEPTNO, TO_CHAR(HIREDATE, 'YYYY'));