--2022/11/09
--P.239
--1번 문제
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
    FROM DEPT D, EMP E
    WHERE D.DEPTNO = E.DEPTNO AND E.SAL>2000;

--2번 문제
SELECT D.DEPTNO, D.DNAME,
       TRUNC(AVG(E.SAL),0) AS AVG_SAL,
       MAX(E.SAL) AS MAX_SAL, MIN(E.SAL) AS MIN_SAL,
       COUNT(E.SAL) AS CNT
    FROM DEPT D, EMP E
    WHERE D.DEPTNO = E.DEPTNO
    GROUP BY D.DEPTNO, D.DNAME;

--3번 문제
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.JOB, E.SAL
    FROM DEPT D, EMP E
    WHERE D.DEPTNO = E.DEPTNO(+)
    ORDER BY D.DEPTNO, E.ENAME;

--4번 문제
SELECT D.DEPTNO, D.DNAME, E1.EMPNO, E1.ENAME, E1.MGR, E1.SAL, 
       S.LOSAL, S.HISAL, S.GRADE,
       E2.EMPNO AS MGR_EMPNO, E2.ENAME AS MGR_ENAME
    FROM EMP E1, DEPT D, SALGRADE S, EMP E2
    WHERE E1.DEPTNO(+) = D.DEPTNO
          AND E1.MGR = E2.EMPNO(+)
          AND E1.SAL BETWEEN S.LOSAL AND S.HISAL(+)
    ORDER BY D.DEPTNO, E1.EMPNO;