--2022/11/09 Chap 08
--여러 테이블을 하나의 테이블처럼 사용하는 조인
SELECT COUNT(*) FROM EMP;
SELECT COUNT(*) FROM DEPT;

SELECT COUNT(*) FROM EMP, DEPT;

SELECT ENAME, DNAME, LOC
    FROM EMP, DEPT
    WHERE ENAME='SMITH' AND EMP.DEPTNO=DEPT.DEPTNO;

--등가조인
SELECT E.ENAME, D.DNAME, D.LOC, E.DEPTNO
    FROM EMP E, DEPT D
    WHERE ENAME='SMITH' AND E.DEPTNO=D.DEPTNO;

--P.222 실습8-6
SELECT E.EMPNO, E.ENAME, E.SAL, D.DEPTNO, D.DNAME, D.LOC
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO AND SAL>=3000;
   
--P.223 복습문제
SELECT E.EMPNO, E.ENAME, E.SAL, D.DEPTNO, D.DNAME, D.LOC
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO AND SAL<=2500 AND E.EMPNO<=9999;

--비등가 조인
--P.224 실습8-7
SELECT E.ENAME, S.GRADE
    FROM EMP E, SALGRADE S
    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;

--자체조인
--P.227 실습 8-8
SELECT E1.EMPNO, E1.ENAME, E1.MGR, E2.EMPNO AS MGR_EMPNO, E2.ENAME AS MGR_ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO;


SELECT E1.EMPNO, E1.ENAME, E2.ENAME AS MGR_ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO AND E1.ENAME='SMITH';

--외부조인
--P.229 실습 8-9 왼쪽 외부조인
SELECT E1.EMPNO, E1.ENAME, E1.MGR, E2.EMPNO AS MGR_EMPNO, E2.ENAME AS MGR_NAME
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO(+)
ORDER BY E1.EMPNO;

--P.229 실습 8-10 오른쪽 외부조인
SELECT E1.EMPNO, E1.ENAME, E1.MGR, E2.EMPNO AS MGR_EMPNO, E2.ENAME AS MGR_NAME
FROM EMP E1, EMP E2
WHERE E1.MGR(+) = E2.EMPNO
ORDER BY E1.EMPNO;