--2022/11/10
--1번 문제 : COUNTRIES테이블에 다음표에 해당하는 데이터를 삽입
--COUNTRY_ID  COUNTRY_NAME  REGION_ID
--   AT          Austria       1
--   NO          Norway        1
--   ID          Indonesia     3
--   TR          Turkey        4

SELECT * FROM COUNTRIES;

INSERT INTO COUNTRIES(COUNTRY_ID, COUNTRY_NAME, REGION_ID)
VALUES('AT','Austria',1);

INSERT INTO COUNTRIES(COUNTRY_ID, COUNTRY_NAME, REGION_ID)
VALUES('NO','Norway',1);

INSERT INTO COUNTRIES(COUNTRY_ID, COUNTRY_NAME, REGION_ID)
VALUES('ID','Indonesia',3);

INSERT INTO COUNTRIES(COUNTRY_ID, COUNTRY_NAME, REGION_ID)
VALUES('TR','Turkey',4);

--2번 문제 : DEPARTMENTS 테이블에 다음 표에 해당하는 데이터를 삽입
--DEPARTMENT_ID  DEPARTMENT_NAME  MANAGER_ID  LOCATION_ID
--    280        Advertising         200         1700
--    290        Sales Support       145         1700
--    300        Education           NULL        1700
--    310        E-Commerce          NULL        1700

SELECT * FROM DEPARTMENTS;

INSERT INTO DEPARTMENTS(DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID)
VALUES(280,'Advertising',200,1700);

INSERT INTO DEPARTMENTS(DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID)
VALUES(290,'Sales Support',145,1700);

INSERT INTO DEPARTMENTS(DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID)
VALUES(300,'Education',NULL,1700);

INSERT INTO DEPARTMENTS(DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID)
VALUES(310,'E-Commerce',NULL,1700);

--3번 문제 : DEPARTMENTS 테이블에 다음 표에 해당하는 데이터를 변경
--DEPARTMENT_ID  DEPARTMENT_NAME  MANAGER_ID  LOCATION_ID
--    280        Advertising         200         2000
--    290        Sales Support       145         2000
--    300        Education           102         2000
--    310        E-Commerce          102         2000

UPDATE DEPARTMENTS SET MANAGER_ID = 102
WHERE DEPARTMENT_ID IN(300,310);

UPDATE DEPARTMENTS SET LOCATION_ID = 2000
WHERE DEPARTMENT_ID IN(280,290,300,310);

SELECT * FROM DEPARTMENTS;

DELETE FROM COUNTRIES WHERE COUNTRY_ID IN('AT','NO','ID','TR');
DELETE FROM DEPARTMENTS WHERE DEPARTMENT_ID IN(280,290,300,310);

COMMIT;
