--2022-11-07
--1번 문제 : JOBS테이블의 JOB_TITLE을 소문자, 대문자로 출력하라.
SELECT JOB_TITLE, LOWER(JOB_TITLE) AS 소문자, UPPER(JOB_TITLE) AS 대문자
FROM JOBS;

--2번 문제 : EMPLOYEES테이블의 FIRST_NAME과 LAST_NAME을 출력하되,
--FIRST_NAME은 첫 글자만 출력하라.
SELECT FIRST_NAME, SUBSTR(FIRST_NAME,1,1), LAST_NAME FROM EMPLOYEES;

--3번 문제 : EMPLOYEES테이블의 JOB_ID에서 REP를 REPRESENTATIVE로 출력하라.
SELECT JOB_ID, REPLACE(JOB_ID,'REP','REPRESENTATIVE') FROM EMPLOYEES;

--4번 문제 : EMPLOYEES테이블의 FIRST_NAME과 LAST_NAME을 합쳐서 출력하되,
--FIRST_NAME은 첫 글자만 출력하고 FIRST_NAME과 LAST_NAME 사이에 공백을 주어라.
SELECT CONCAT(SUBSTR(FIRST_NAME,1,1),CONCAT(' ',LAST_NAME))
FROM EMPLOYEES;